### ISSUE TITLE
Assets in doInBackground throw NullPointerException

### ISSUE THREAD

**Issue by Florent1510** [cmusphinx/pocketsphinx-android-demo#12]
Hey, I can't explain what's happening.. Does somebody know?

12-03 20:55:39.334 10097 10111 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
12-03 20:55:39.334 10097 10111 E AndroidRuntime: Process: com.fa.ve, PID: 10097
12-03 20:55:39.334 10097 10111 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:309)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
12-03 20:55:39.334 10097 10111 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at edu.cmu.pocketsphinx.Assets.syncAssets(Assets.java:256)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at com.fa.ve.MainActivity$5.doInBackground(MainActivity.java:303)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at com.fa.ve.MainActivity$5.doInBackground(MainActivity.java:298)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:295)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
12-03 20:55:39.334 10097 10111 E AndroidRuntime:        ... 4 more
12-03 20:55:39.344 20496 21573 W ActivityManager:   Force finishing activity com.fa.ve/.MainActivity
1

**Comment by Florent1510** [comment]
Fixed it by cleaning the project.
