### ISSUE TITLE
Library crashes on neutab g7 (Android 5.1)

### ISSUE THREAD

**Issue by willblaschko** [cmusphinx/pocketsphinx-android-demo#20]
Library is crashing when initializing the SpeechRecognizer with the following call:

```
recognizer = defaultSetup()
                                .setAcousticModel(new File(assetsDir, "en-us-ptm"))
                                .setDictionary(new File(assetsDir, "cmudict-en-us.dict"))
                                // Use context-independent phonetic search, context-dependent is too slow for mobile
                                .setBoolean("-allphone_ci", true)
                                .getRecognizer();
```

No issues on any other device than the one above. Below is the stack trace:

```
Non-fatal Exception: java.lang.IllegalArgumentException
       at android.media.AudioRecord.<init>(AudioRecord.java:277)
       at android.media.AudioRecord.<init>(AudioRecord.java:233)
       at edu.cmu.pocketsphinx.SpeechRecognizer.<init>(SpeechRecognizer.java:82)
       at edu.cmu.pocketsphinx.SpeechRecognizerSetup.getRecognizer(SpeechRecognizerSetup.java:74)
       at com.willblaschko.android.alexalistens.MainActivity$SettingsFragment$6.doInBackground(MainActivity.java:261)
       at com.willblaschko.android.alexalistens.MainActivity$SettingsFragment$6.doInBackground(MainActivity.java:245)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by mbait** [comment]
Make sure that your device supports the required sample rate. From [official docs](https://developer.android.com/reference/android/media/AudioRecord.html):
> 44100Hz is currently the only rate that is guaranteed to work on all devices, but other rates such as 22050, 16000, and 11025 may work on some devices.

**Comment by willblaschko** [comment]
Does this mean it won't default to 44100Hz with the defaultSetup() call? If so, I can add it in to see if it fixes the problem.

**Comment by mbait** [comment]
No, the default is either 8KHz or 16KHz - search in the logcat output for
"samprate". If you set it to 44Khz it won't work, because you need to match
the sample rate of the acoustic model.

On Thu, May 26, 2016 at 2:14 PM, Will Blaschko <notifications@github.com>
wrote:

> Does this mean it won't default to 44100Hz with the defaultSetup() call?
> If so, I can add it in to see if it fixes the problem.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/cmusphinx/pocketsphinx-android-demo/issues/20#issuecomment-221996756>
>



-- 
Sincerely, Alexander
