### ISSUE TITLE
Exception egtting on Redmi 3s (Android 6.01)

### ISSUE THREAD

**Issue by vishwasrao** [cmusphinx/pocketsphinx-android-demo#25]
Hi,
I am trying this demo on my Redmi 3S which has Android 6.0.1
But getting below error.

**java.lang.RuntimeException: An error occurred while executing doInBackground()**
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
**Caused by: java.lang.RuntimeException: Decoder_setKeyphrase returned -1**
at edu.cmu.pocketsphinx.PocketSphinxJNI.Decoder_setKeyphrase(Native Method)
at edu.cmu.pocketsphinx.Decoder.setKeyphrase(Decoder.java:155)
at edu.cmu.pocketsphinx.SpeechRecognizer.addKeyphraseSearch(SpeechRecognizer.java:259)
at edu.cmu.pocketsphinx.demo.PocketSphinxActivity.setupRecognizer(PocketSphinxActivity.java:232)
at edu.cmu.pocketsphinx.demo.PocketSphinxActivity.access$000(PocketSphinxActivity.java:55)
at edu.cmu.pocketsphinx.demo.PocketSphinxActivity$1.doInBackground(PocketSphinxActivity.java:107)
at edu.cmu.pocketsphinx.demo.PocketSphinxActivity$1.doInBackground(PocketSphinxActivity.java:101)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more

Any suggestions will be highly appreciated.

Thanks,
Vishwas

**Comment by nshmyrev** [comment]
You already asked this question here:

http://stackoverflow.com/questions/40301781/pocketsphinx-on-android-exception-decoder-setkeyphrase-returned-1

Lets continue on stackoverflow, you need to provide logcat output for further help.
