### ISSUE TITLE
App crashing with exception :

### ISSUE THREAD

**Issue by imneeraj** [cmusphinx/pocketsphinx-android-demo#28]
exception : 
' Caused by: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader'

 java.lang.RuntimeException: An error occurred while executing doInBackground()
                      at android.os.AsyncTask$3.done(AsyncTask.java:309)
                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                      at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
                   Caused by: java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-support-annotations-25.1.0_b02ac6e364c71fa0306bce48db25c7d4709a4bfe-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-pocketsphinx-android-5prealpha-nolib_0aa14585f0ac20d7c7b1b354e2474468dac5b9b9-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-transition-25.1.0_bbbace6f3cf8fd2d5151fc5e1fe394d18ac2f4c2-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-support-vector-drawable-25.1.0_fd21bbc33fcc0bb85e6b7374f5712378d5644230-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-support-v4-25.1.0_80240033933550bbf421fa3e2ddabc8ca896d435-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-support-media-compat-25.1.0_7bfb2a960a0efc0a37e45a0ca8fe83deebcef70d-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-support-fragment-25.1.0_28ae5f6969d9fda82842bd2592883422d7289774-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-support-core-utils-25.1.0_fd66325c44621f09143f90ab62cf5fa2e6158021-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-support-core-ui-25.1.0_73300684736cbe337978fbf5a0c7eacdccab0a57-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-support-compat-25.1.0_719df2e4f2546ac24e475703a1fe590a2eed218a-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-recyclerview-v7-25.1.0_ec31a3d2c166f0ca725bb5e17f3baa44c56f83fa-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-com.android.support-design-25.1.0_67e228634ae2ddcc7216e4244d06f61ecbe59171-classes.dex", dex file "/data/data/com.example.neeraj.speechbuzzer/files/instant-run/dex/slice-co

**Comment by nshmyrev** [comment]
You need to provide a complete log.
