### ISSUE TITLE
Can i turn off use of arm64. My application support armv7 only

### ISSUE THREAD

**Issue by yasharoiko** [cmusphinx/pocketsphinx-android-demo#56]
When enable pocketsphinx-android-5prealpha-release  in my project i got error starting my application

Fatal Exception: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.wonhada.test-1/base.apk"],nativeLibraryDirectories=[/data/app/com.wonhada.test-1/lib/arm64, /data/app/com.wonhada.test-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "liblua.so"
       at java.lang.Runtime.loadLibrary0(Runtime.java:984)
       at java.lang.System.loadLibrary(System.java:1530)
       at com.ansca.corona.JavaToNativeShim.<clinit>(JavaToNativeShim.java:115)
       at com.ansca.corona.JavaToNativeShim.useJavaLuaErrorHandler(JavaToNativeShim.java:261)
       at com.ansca.corona.CoronaEnvironment.setLuaErrorHandler(CoronaEnvironment.java:391)
       at com.ansca.corona.CoronaEnvironment.<clinit>(CoronaEnvironment.java:50)
       at com.ansca.corona.CoronaEnvironment.addRuntimeListener(CoronaEnvironment.java:434)
       at com.wonhada.test.CoronaApplication.onCreate(CoronaApplication.java:22)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5555)
       at android.app.ActivityThread.-wrap2(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1576)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:6281)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

I am using Corona SDK and they said
Looks like something is still trying to use arm64. While we are working on support for that, we only support armv7.
Rob

I use pocketsphinx-android-5prealpha-release.aar 

Is it possible to recompile it to not use arm64?

**Comment by nshmyrev** [comment]
> Is it possible to recompile it to not use arm64?

Yes, you can also simply remove the file from the packed jar with an archive editor.
